# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Authcurl < Formula
  desc "authcurl - authenticated curl wrapper"
  homepage "https://github.com/nguyenvanduocit/authcurl"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/authcurl/releases/download/v0.1.0/authcurl_0.1.0_darwin_amd64.zip"
      sha256 "e7160402ee17783a79677dc2e90930c71f01f7808055c6c6764057241ad42ad0"

      define_method(:install) do
        bin.install "authcurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/authcurl/releases/download/v0.1.0/authcurl_0.1.0_darwin_arm64.zip"
      sha256 "9a6df56e4e8e8501dbedf44d7181b92326fb1d8a24f3a28ffdcbfbc2a8814785"

      define_method(:install) do
        bin.install "authcurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/authcurl/releases/download/v0.1.0/authcurl_0.1.0_linux_amd64.tar.gz"
      sha256 "1fc9bbdf601c77f09d20eef3e3f9d5f9499ca5f800709841e3014c1271f50073"
      define_method(:install) do
        bin.install "authcurl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/authcurl/releases/download/v0.1.0/authcurl_0.1.0_linux_arm64.tar.gz"
      sha256 "06630f9550df7138c102507a761ebbca62e0c2046bb2c765844e45c2cb171b8d"
      define_method(:install) do
        bin.install "authcurl"
      end
    end
  end
end
