# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfluenceCli < Formula
  desc "confluence-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/confluence-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-cli_darwin_amd64.tar.gz"
      sha256 "6f3854d6adc0d5818f67229ab8db33a3f83000841eee7c10cc857f31a8e420ac"

      define_method(:install) do
        bin.install "confluence-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-cli_darwin_arm64.tar.gz"
      sha256 "0f65545dd3edc1d331c427b063a56efe11303ca1b0e6dbe202aae910318cc1c1"

      define_method(:install) do
        bin.install "confluence-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-cli_linux_amd64.tar.gz"
      sha256 "978d11a60321939ace3fcf9272663aa852b6fcf89a981e3ea3ceb0dde13b06c5"
      define_method(:install) do
        bin.install "confluence-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-cli_linux_arm64.tar.gz"
      sha256 "ce10cf64273342a6b953e5251640301e61036aad6e233c5e353471a684843d55"
      define_method(:install) do
        bin.install "confluence-cli"
      end
    end
  end
end
