# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ConfluenceMcp < Formula
  desc "confluence-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/confluence-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-mcp_darwin_amd64.tar.gz"
      sha256 "65209fde3f8919d9f3a42828d112c604dfced6a0ce355ab408e8d27c3ca9d2cb"

      define_method(:install) do
        bin.install "confluence-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-mcp_darwin_arm64.tar.gz"
      sha256 "359eb3aa4bdb713201db763069576f037c1da1bab284ff81713d8b6be82d627e"

      define_method(:install) do
        bin.install "confluence-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-mcp_linux_amd64.tar.gz"
      sha256 "261a682c7c11ad0d02b65dde6c00be89a62323276f2742eb507bcb50fe9df418"
      define_method(:install) do
        bin.install "confluence-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/confluence-mcp/releases/download/v1.0.3/confluence-mcp_linux_arm64.tar.gz"
      sha256 "c31750b99618430e3f3ec2f8d9b59bf12760c7eece448ed8553717e2c5e0f1ad"
      define_method(:install) do
        bin.install "confluence-mcp"
      end
    end
  end
end
