# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FetchKit < Formula
  desc "fetch-kit - MCP server"
  homepage "https://github.com/nguyenvanduocit/fetch-kit"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-kit_darwin_amd64.tar.gz"
      sha256 "cd8c597e93ddecda750f7aef195029aa2ebe083ab6e8f503930b78cf747f7daa"

      define_method(:install) do
        bin.install "fetch-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-kit_darwin_arm64.tar.gz"
      sha256 "271f33ecbd2424adf1e3cba1f20ece80f61f5129624381e787854234c5c2a360"

      define_method(:install) do
        bin.install "fetch-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-kit_linux_amd64.tar.gz"
      sha256 "9cdded7c0792908bf8b3f4809e670acbe6cabff92af13252b606ce1e2c0d387e"
      define_method(:install) do
        bin.install "fetch-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-kit_linux_arm64.tar.gz"
      sha256 "071431c9ab4e415c2309824b6790d252b02ce07006c0c9d7a62fc37fda56c4d0"
      define_method(:install) do
        bin.install "fetch-kit"
      end
    end
  end
end
