# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FetchCli < Formula
  desc "fetch-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/fetch-kit"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-cli_darwin_amd64.tar.gz"
      sha256 "461d2c47cc100c67081fa768c3ee909c314076085a3b491ef5230a5eb20ade5d"

      define_method(:install) do
        bin.install "fetch-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-cli_darwin_arm64.tar.gz"
      sha256 "5262583f943c9f1e8cffcc49519a703aca9cfbd794d1cd262d444564f68ecc85"

      define_method(:install) do
        bin.install "fetch-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-cli_linux_amd64.tar.gz"
      sha256 "08cc859bea6550501444e511284eab0fb0f8d6ceada4723f541be595a7f95cd0"
      define_method(:install) do
        bin.install "fetch-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/fetch-kit/releases/download/v1.1.3/fetch-cli_linux_arm64.tar.gz"
      sha256 "a66e067375836fb3ae39d289773275b8da82c08404bc975c226431b4588196f6"
      define_method(:install) do
        bin.install "fetch-cli"
      end
    end
  end
end
