# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubCli < Formula
  desc "github-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/github-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-cli_darwin_amd64.tar.gz"
      sha256 "2222ce5d0538bfa60c6e1ade84bab74097796e35ceab4246176f7df256f224f2"

      define_method(:install) do
        bin.install "github-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-cli_darwin_arm64.tar.gz"
      sha256 "3548a4470130f1908fba6a8d75d61aca990756b733ca2c95942cbdf96f331894"

      define_method(:install) do
        bin.install "github-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-cli_linux_amd64.tar.gz"
      sha256 "fc59bfba3060d97dd205e8f67bd19c8183455d520feecab5231ae10410a79812"
      define_method(:install) do
        bin.install "github-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-cli_linux_arm64.tar.gz"
      sha256 "f179667132c83d67e7d5c4fb43d4c1c1a67a2a8655f0ee83b3524cb81c69f7fa"
      define_method(:install) do
        bin.install "github-cli"
      end
    end
  end
end
