# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GithubMcp < Formula
  desc "github-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/github-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-mcp_darwin_amd64.tar.gz"
      sha256 "1c4c54ba08b5385dba0a69ebb619024fd765f414e986705a4633a10f386698c3"

      define_method(:install) do
        bin.install "github-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-mcp_darwin_arm64.tar.gz"
      sha256 "2ad2c352c25bdad70d81b45381b1316881762a6805da9c8ace5a564fd23ceb9e"

      define_method(:install) do
        bin.install "github-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-mcp_linux_amd64.tar.gz"
      sha256 "73cb2dce7a5cf5e811eb13e52238ceeafdea68cd2aa46e9bf0877e8d159dcc18"
      define_method(:install) do
        bin.install "github-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/github-mcp/releases/download/v1.0.3/github-mcp_linux_arm64.tar.gz"
      sha256 "33dd759e3c2e7081e61676c570afbc29afa9e40348bd30ffa2a91282cd5eea01"
      define_method(:install) do
        bin.install "github-mcp"
      end
    end
  end
end
