# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabCli < Formula
  desc "gitlab-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/gitlab-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-cli_Darwin_x86_64.tar.gz"
      sha256 "8e8f2f02db48ce6ac47300e3c80ba7e89781f51bd16af2f565d319ae6cabc585"

      define_method(:install) do
        bin.install "gitlab-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-cli_Darwin_arm64.tar.gz"
      sha256 "618e2b5ff5a0f6543382a939990d8c6d332d0abe1fd2d8460578a1ac881ef7de"

      define_method(:install) do
        bin.install "gitlab-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-cli_Linux_x86_64.tar.gz"
      sha256 "cd631869a992fe3b321d64e617f1c2a5af32906bdc783ca3c810adde4c8b2c7b"
      define_method(:install) do
        bin.install "gitlab-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-cli_Linux_arm64.tar.gz"
      sha256 "fdbe6e498c326b6f159daf6efd224bce31e29b07022c5bc50975f304184d49aa"
      define_method(:install) do
        bin.install "gitlab-cli"
      end
    end
  end
end
