# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GitlabMcp < Formula
  desc "gitlab-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/gitlab-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-mcp_Darwin_x86_64.tar.gz"
      sha256 "331061f1040c9ddf4953b4154e1a4f9e37e5791d418761e118655b5e0c618dfb"

      define_method(:install) do
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-mcp_Darwin_arm64.tar.gz"
      sha256 "4d5263109f647c51c98f9a906fe28241db59e190eacb3d17bd5f94a2cde855fc"

      define_method(:install) do
        bin.install "gitlab-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-mcp_Linux_x86_64.tar.gz"
      sha256 "65e13f6d09e7595af91459772bb4816c8642086391c1ca90d2d49caa27fbd387"
      define_method(:install) do
        bin.install "gitlab-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/gitlab-mcp/releases/download/v1.0.3/gitlab-mcp_Linux_arm64.tar.gz"
      sha256 "02688e9c4fd8ced5682a45caaf7cf2509a8efc5af096c27cdf687a29a89dc141"
      define_method(:install) do
        bin.install "gitlab-mcp"
      end
    end
  end
end
