# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleChatMcp < Formula
  desc "google-chat-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/google-chat-mcp"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-mcp_darwin_amd64.tar.gz"
      sha256 "62f7b84222187541bc2ff5f79f02ed2d5973c69abde5cf72dfe244068389782e"

      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-mcp_darwin_arm64.tar.gz"
      sha256 "e9ffab35722e590a7b4ab617b9871714deedbd6a77377db182e782f0c03b556c"

      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-mcp_linux_amd64.tar.gz"
      sha256 "42fd36e737cc7414fedfdfca8d21d602e117b0c191d3ea54b61bf956be8e203e"
      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-mcp_linux_arm64.tar.gz"
      sha256 "1d5706bd9eddee0c51d25156a9d5af8a3984fd10c76c56a475962dd7ebe18f10"
      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
  end
end
