# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleChatCli < Formula
  desc "google-chat-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/google-chat-mcp"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-cli_darwin_amd64.tar.gz"
      sha256 "6715bd4205cbf7f2eaebb85f89951e52054685c27be7a00e6120850eebb3ea35"

      define_method(:install) do
        bin.install "google-chat-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-cli_darwin_arm64.tar.gz"
      sha256 "0b3983c0d307e9b14c5aed2a50a3efa146298185ad295fbafef47673fd6e8320"

      define_method(:install) do
        bin.install "google-chat-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-cli_linux_amd64.tar.gz"
      sha256 "defcfe1d408acfcae674c837f9d4a10ce199a04641e0e3d1c20ca9695c1cee49"
      define_method(:install) do
        bin.install "google-chat-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.0/google-chat-cli_linux_arm64.tar.gz"
      sha256 "8c9955c2dc941868fb9f867734147317ba52151e42f438e16b3e0b983271eb6e"
      define_method(:install) do
        bin.install "google-chat-cli"
      end
    end
  end
end
