# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleMcp < Formula
  desc "google-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/google-mcp"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-mcp_darwin_amd64.tar.gz"
      sha256 "9c6c19068164e34e299623c0a0d1de937eca7aa36c388abd89bd11d194a25fc3"

      define_method(:install) do
        bin.install "google-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-mcp_darwin_arm64.tar.gz"
      sha256 "196b139e22248a6b9af17eba1014db21be984d12b181fc84e22ecc6cbdb211d6"

      define_method(:install) do
        bin.install "google-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-mcp_linux_amd64.tar.gz"
      sha256 "c74489abb41ae6f30e6929ea23a36225aac601f9e36fa1dfd83ed65d7100c035"
      define_method(:install) do
        bin.install "google-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-mcp_linux_arm64.tar.gz"
      sha256 "a5a6a1dd389419cd51afb4425833b08cfe28e230425f68d3b28623069b9d6275"
      define_method(:install) do
        bin.install "google-mcp"
      end
    end
  end
end
