# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleChatMcp < Formula
  desc "google-chat-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/google-chat-mcp"
  version "1.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.1/google-chat-mcp_darwin_amd64.tar.gz"
      sha256 "b5e3ec68b98fa8ff854e09e01bbbd0f4a3e8967b49cec70a44c76ee2241fa3d4"

      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.1/google-chat-mcp_darwin_arm64.tar.gz"
      sha256 "f90a33c2ca1501225c5a1bb457fe3f9661bbfd9beb2738138043f2cdc7423167"

      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.1/google-chat-mcp_linux_amd64.tar.gz"
      sha256 "8affb1febbff39013659995f02afea41ef99d6e2bef29357d3748b834e6eeb35"
      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-chat-mcp/releases/download/v1.0.1/google-chat-mcp_linux_arm64.tar.gz"
      sha256 "8cc89583face793c85b36f3bdc2787434ca12d65db80c63946f3c8600c48901c"
      define_method(:install) do
        bin.install "google-chat-mcp"
      end
    end
  end
end
