# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoogleCli < Formula
  desc "google-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/google-mcp"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-cli_darwin_amd64.tar.gz"
      sha256 "a6e9a462caac5fa746f4ee5656def7e79366f018e4da11e2c74057036abaae32"

      define_method(:install) do
        bin.install "google-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-cli_darwin_arm64.tar.gz"
      sha256 "8a5294ef958ab70658387d850036a1101c3d5d4886d0c16d2cf27074dc00f999"

      define_method(:install) do
        bin.install "google-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-cli_linux_amd64.tar.gz"
      sha256 "fd864978329fc6e2e9d12a08df14e77fbd292bb9bd6161b0b0688313180835dd"
      define_method(:install) do
        bin.install "google-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/google-mcp/releases/download/v1.1.3/google-cli_linux_arm64.tar.gz"
      sha256 "747e4c9a724eef247e11a3d12d11dfaa5503e189db9fe73d5ea1e6783a410f80"
      define_method(:install) do
        bin.install "google-cli"
      end
    end
  end
end
