# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraMcp < Formula
  desc "jira-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/jira-mcp"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.1.0/jira-mcp_darwin_amd64.tar.gz"
      sha256 "f7b709b378b8d93383f588170f9f38e2f8d7032bd06044c6e80ace29bb968af1"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.1.0/jira-mcp_darwin_arm64.tar.gz"
      sha256 "798b9c38407460b2e8b23507bf16f7b13e7179519a8f87bb8594449e5198a319"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.1.0/jira-mcp_linux_amd64.tar.gz"
      sha256 "27fee0785bae22ef7b12ac5015fbc130331ce02dbf6105cba6b8b53f84612eee"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.1.0/jira-mcp_linux_arm64.tar.gz"
      sha256 "48dbd34cea753c42f176a7b8f29bab6adefc85e4c8b3a867638b724ef4a6a06d"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end
end
