# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraMcp < Formula
  desc "jira-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/jira-mcp"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.0/jira-mcp_darwin_amd64.tar.gz"
      sha256 "3db39c964d1959ca255630fdec725cd7e1d8b3d0e85f07cd1df94851c4e6b97d"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.0/jira-mcp_darwin_arm64.tar.gz"
      sha256 "544a3ec8a10bf4aadcfb3b64a8d08cbb965141848e5bf0260d3d322116dc76a6"

      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.0/jira-mcp_linux_amd64.tar.gz"
      sha256 "e8044030a47b865138183dcdc5d26b575f5d9b4a8f05ea37127e68983a048cf2"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.0/jira-mcp_linux_arm64.tar.gz"
      sha256 "90c74904306f509ddb71ed24c7f2b2495667199e7935053be7605fbcba9ff4a4"
      define_method(:install) do
        bin.install "jira-mcp"
      end
    end
  end
end
