# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "jira-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/jira-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.0.3/jira-cli_darwin_amd64.tar.gz"
      sha256 "5989ed311742d03c7b1a30fb71be5dca7229ee5bffb7ff79acdbfe43d1c4566d"

      define_method(:install) do
        bin.install "jira-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.0.3/jira-cli_darwin_arm64.tar.gz"
      sha256 "01423cf699d23ef356df810f53a2fe0d908a087624582506e5d9d32f830e0cc6"

      define_method(:install) do
        bin.install "jira-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.0.3/jira-cli_linux_amd64.tar.gz"
      sha256 "ca43b77a0b22351f9a41c3888c5f1b3123b25006207ec6b662cdb077f7a998dc"
      define_method(:install) do
        bin.install "jira-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.0.3/jira-cli_linux_arm64.tar.gz"
      sha256 "d4a31a2bb1a2ce35cc9d8b903edc0a5ace0ae6c3336028f36c8f1cce4c7ce675"
      define_method(:install) do
        bin.install "jira-cli"
      end
    end
  end
end
