# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class JiraCli < Formula
  desc "jira-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/jira-mcp"
  version "1.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.1/jira-cli_darwin_amd64.tar.gz"
      sha256 "3062e20e1bea08c2e9b98775325c63d26c55aff3fb4d360faa781aeb86e04574"

      define_method(:install) do
        bin.install "jira-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.1/jira-cli_darwin_arm64.tar.gz"
      sha256 "0bbd14e46f39ec31971551c0d7f8fb5ea54f6e74d7b3cdd35974bf4b35b065ad"

      define_method(:install) do
        bin.install "jira-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.1/jira-cli_linux_amd64.tar.gz"
      sha256 "eef9b710653cfdebf9458085096ddc1709cc771870225b34f50fac1a03c55ab7"
      define_method(:install) do
        bin.install "jira-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/jira-mcp/releases/download/v1.2.1/jira-cli_linux_arm64.tar.gz"
      sha256 "cba010916a57deb056fa450fec4c42e2d901d0057a3f9c3a2783f63a3888eeac"
      define_method(:install) do
        bin.install "jira-cli"
      end
    end
  end
end
