# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyrecap < Formula
  desc "Terminal dashboard for the coding-agent sessions running in this directory — who is working, who is waiting for you, and a plain-language recap."
  homepage "https://github.com/nguyenvanduocit/lazyrecap"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.1.0/lazyrecap_0.1.0_darwin_x86_64.tar.gz"
      sha256 "cdbf38e5e725ab0df3ebc2b895733877e5bb12cd28c261a35b7e0ef6b7f2c4e0"

      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.1.0/lazyrecap_0.1.0_darwin_arm64.tar.gz"
      sha256 "4575ad37789dde4a7be51c41f7752a1ad83d1c941c4cfc0242d8f017f5c0d8a1"

      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.1.0/lazyrecap_0.1.0_linux_x86_64.tar.gz"
      sha256 "5e111131eab17804e83a56b3bdbb4484001dbab7f68739c3ac6eb51223b513de"
      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.1.0/lazyrecap_0.1.0_linux_arm64.tar.gz"
      sha256 "8f9472ca52741bec107d98df5b39c496c12d26f1e8770f4e6f14728d325c5b68"
      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
  end

  test do
    assert_match "lazyrecap #{version}", shell_output("#{bin}/lazyrecap --version")
  end
end
