# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyrecap < Formula
  desc "Terminal dashboard for the coding-agent sessions running in this directory — who is working, who is waiting for you, and a plain-language recap."
  homepage "https://github.com/nguyenvanduocit/lazyrecap"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.2.0/lazyrecap_0.2.0_darwin_x86_64.tar.gz"
      sha256 "973fc31fc3708ad3c11e9286e16609e230832e481ec7bae2fbff932ce29ffc91"

      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.2.0/lazyrecap_0.2.0_darwin_arm64.tar.gz"
      sha256 "c256c2b04fe7abe91f412432fef256e214ed4fd2d0174f1665ca8b351dadb103"

      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.2.0/lazyrecap_0.2.0_linux_x86_64.tar.gz"
      sha256 "ea553919c74c00cadfde781402642307f5e887d39aa10e2b757c59e0094ceea5"
      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/lazyrecap/releases/download/v0.2.0/lazyrecap_0.2.0_linux_arm64.tar.gz"
      sha256 "d2334072a99964bb75d52faa5548a8cbce60d2e2ab2da110327edf0c1f92d29c"
      define_method(:install) do
        bin.install "lazyrecap"
      end
    end
  end

  test do
    assert_match "lazyrecap #{version}", shell_output("#{bin}/lazyrecap --version")
  end
end
