# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RagKit < Formula
  desc "rag-kit - MCP server"
  homepage "https://github.com/nguyenvanduocit/rag-kit"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-kit_darwin_amd64.tar.gz"
      sha256 "bf7d44979315c5bef3afca28611b193e7d841cd44f767f44f41b639142728f2b"

      define_method(:install) do
        bin.install "rag-kit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-kit_darwin_arm64.tar.gz"
      sha256 "2fea00ce5d97d81dae87ab1d9c6724f383e1377ac33b3d6ec37cce2ae8fb21fb"

      define_method(:install) do
        bin.install "rag-kit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-kit_linux_amd64.tar.gz"
      sha256 "e19ab1c94155801bcce7e54518e9ecc1559691993388b0a13a33e7d6ad9b495c"
      define_method(:install) do
        bin.install "rag-kit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-kit_linux_arm64.tar.gz"
      sha256 "162e07e59d937a717b36c729bbe072555098617e79d7803d659d81ff94650e8f"
      define_method(:install) do
        bin.install "rag-kit"
      end
    end
  end
end
