# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RagCli < Formula
  desc "rag-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/rag-kit"
  version "1.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-cli_darwin_amd64.tar.gz"
      sha256 "469e3d252f5d2aea1fc6f35fe0e04ccc34659bef6925fb9dc23d9be6df6a2ca8"

      define_method(:install) do
        bin.install "rag-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-cli_darwin_arm64.tar.gz"
      sha256 "da34c9f4ac8fd31508388f670126fc8b67601fa2035738b52651fd29bd4e9e40"

      define_method(:install) do
        bin.install "rag-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-cli_linux_amd64.tar.gz"
      sha256 "f00eb3678601851bba0ad5cb20285aa13a015428bc0fcd2793e538f8568cd51a"
      define_method(:install) do
        bin.install "rag-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/rag-kit/releases/download/v1.0.4/rag-cli_linux_arm64.tar.gz"
      sha256 "bfe9d119a4640d604936fdbbea5a87dde003dfa012dbea127dcc328ba582a926"
      define_method(:install) do
        bin.install "rag-cli"
      end
    end
  end
end
