# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScriptMcp < Formula
  desc "script-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/script-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-mcp_darwin_amd64.tar.gz"
      sha256 "315e7531eabb9d10404cbda19e07ef918929c6ce9e594fc1d0d3c5bb4d02eef6"

      define_method(:install) do
        bin.install "script-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-mcp_darwin_arm64.tar.gz"
      sha256 "7c5e89a43a5497230c75a2cb2359d5f70c33d445f1be3584de90b0dc4dffff68"

      define_method(:install) do
        bin.install "script-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-mcp_linux_amd64.tar.gz"
      sha256 "222327ee5b4722aac2a40756f8040df2f086885d56cdf3a6209f602e245203d6"
      define_method(:install) do
        bin.install "script-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-mcp_linux_arm64.tar.gz"
      sha256 "d6cc2b5fe74b8b000750085746f8ca0e03318b424cfdc01e465982e75287ba8a"
      define_method(:install) do
        bin.install "script-mcp"
      end
    end
  end
end
