# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ScriptCli < Formula
  desc "script-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/script-mcp"
  version "1.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-cli_darwin_amd64.tar.gz"
      sha256 "58ade9ba90e2f977f874d8298201b50bbccb3e17ca41c32cfd4e3cbc77e257a0"

      define_method(:install) do
        bin.install "script-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-cli_darwin_arm64.tar.gz"
      sha256 "709ecc4abf2e5ac769af6e4f3568f91a91d7840db0477d6187b90f3f4cebb945"

      define_method(:install) do
        bin.install "script-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-cli_linux_amd64.tar.gz"
      sha256 "a7a82f397b3e88a348d54a2a8fbdabf84bcaee7969675d0c973e385e557c2569"
      define_method(:install) do
        bin.install "script-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/script-mcp/releases/download/v1.0.3/script-cli_linux_arm64.tar.gz"
      sha256 "65ea90ee48d0e670d9c0eae516d21602a1aee843f2ad2eca3c1b0053cb7fafc5"
      define_method(:install) do
        bin.install "script-cli"
      end
    end
  end
end
