# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XCli < Formula
  desc "x-cli - CLI tool"
  homepage "https://github.com/nguyenvanduocit/x-mcp"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-cli_darwin_amd64.tar.gz"
      sha256 "772e80d57e15acf418ea1bf7b5b606f58807762c4529aa61613a9784d415a5e4"

      define_method(:install) do
        bin.install "x-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-cli_darwin_arm64.tar.gz"
      sha256 "3b23ffab0b411696e6a6cccfe751a14b6d01643aecdae3aec3a961c24ec422ef"

      define_method(:install) do
        bin.install "x-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-cli_linux_amd64.tar.gz"
      sha256 "d2c0f6296fbff53b8c88f3b1352301dc1a5a9b84f87c198f41a1d5e37cf6b09e"
      define_method(:install) do
        bin.install "x-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-cli_linux_arm64.tar.gz"
      sha256 "d7efa680f02bea31983a709ab4f3042fa2d8b106c94d0f3bdd5179f71a7525a1"
      define_method(:install) do
        bin.install "x-cli"
      end
    end
  end
end
