# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class XMcp < Formula
  desc "x-mcp - MCP server"
  homepage "https://github.com/nguyenvanduocit/x-mcp"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-mcp_darwin_amd64.tar.gz"
      sha256 "75b43c6214ecadaf9619b0894dce3190e25b594ef8f387f5dcb9f878597934ba"

      define_method(:install) do
        bin.install "x-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-mcp_darwin_arm64.tar.gz"
      sha256 "1b6aefe1ced1726309789c857bd36f7ee7092b4df280a81daef719c36af5ee0d"

      define_method(:install) do
        bin.install "x-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-mcp_linux_amd64.tar.gz"
      sha256 "cb3e7f957aa870e95e6bcc5a8f93f8a72e57c42c62b9a0ec53807a1f254fdefb"
      define_method(:install) do
        bin.install "x-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nguyenvanduocit/x-mcp/releases/download/v1.0.0/x-mcp_linux_arm64.tar.gz"
      sha256 "c0b68169f28fc22dcd3a5ff18d9dc174a402933c04d02240f6b79e7f641a58df"
      define_method(:install) do
        bin.install "x-mcp"
      end
    end
  end
end
